### ISSUE TITLE
Login funktioniert nicht da Captcha fehlt

### ISSUE THREAD

**Issue by thahnen** [NuGetHub/pr0gramm-api-dokumentation#3]
Ja das was im Titel steht, als Antwort bekommt man nur als Fehler "invalidCaptcha".
Ansonsten alles klärchen ^^

**Comment by fivekWBassMachine** [comment]
"Fix":
- Einstellungen:
  - user > captcha:
    - URL ausfüllen: `https://pr0gramm.com/api/user/captcha`.
  - user > Login:
    - Im Reiter "Body" die keys `token` und `captcha` hinzufügen.
- Loginvorgang:
  - `user > captcha` losschicken. Im Response ist `token` und `captcha` relevant.
  - `captcha` ist ein Bild, das im Browser des Vertrauens einzufügen ist, Zahlen/ Buchstaben kommen in `user > Login > Body > captcha` rein.
  - Der `token` kommt in `user > Login > Body > token` rein.
  - Zuletzt `user > Login` abschicken.
  - ???
  - Profit.
